###### The Docker Compose Configuration file - docker-compose.yml ########
###### It will build an image of the app and use a readily available image for redis #######
#add mount Binding to make editing code easily without down then up compose again 
#you now can edit code when compose is up 
#specific port of python is 3500

version: '3'
services:
  web:
    build: .
    ports:
      - "9000:3500"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "true"
  redis:
    image: "redis:alpine"
